#!/usr/bin/env zsh

ZSHRC_SCRIPT_DIR=${0:a:h}
export ZSHRC_RUNTIME=$ZSHRC_SCRIPT_DIR/../..

# 1. Configure the basic settings from Oh My Zsh
source $ZSHRC_RUNTIME/config/transient/zshrc.ohmyzsh

# 2. Configure platform specific settings
source $ZSHRC_RUNTIME/config/persistent/zshrc.macos
source $ZSHRC_RUNTIME/config/persistent/zshrc.linux
source $ZSHRC_RUNTIME/config/persistent/zshrc.ssh

# 3. Go through overrides
source $ZSHRC_RUNTIME/config/persistent/zshrc.overrides
source $ZSHRC_RUNTIME/config/transient/zshrc.overrides