#!/usr/bin/env zsh

ZSHRC_SCRIPT_DIR=${0:a:h}
export ZSHRC_RUNTIME=$ZSHRC_SCRIPT_DIR/..

# 1. Configure basic Oh My Zsh settings
source $ZSHRC_RUNTIME/config/zshrc.omz

# 2. Configure platform specific overrides
case "$(uname -s)" in
   Darwin)
       source $ZSHRC_RUNTIME/config/zshrc.macos
     ;;
   *)
       source $ZSHRC_RUNTIME/config/zshrc.linux
     ;;
esac

# 3. Configure SSH specific overrides
if [ "$SSH_CONNECTION" ]; then
    source $ZSHRC_RUNTIME/config/zshrc.ssh
fi

# 4. Activate Oh My Zsh
source $ZSH/oh-my-zsh.sh

## 5. Any last changes?
source $ZSHRC_RUNTIME/config/zshrc.last